version: '3.3'

services:

  wordpress:
    image: wordpress
    links:
      - db:nasprojektdb
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: nasprojektdb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:

      - db_data2:/var/lib/mysql


volumes:
  db_data2:
