
version: '3.1'

services:

  wordpress:
    image: wordpress
    links:
      - db:nasprojektdb
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: nasprojektdb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:

      - db_data:/var/lib/mysql


volumes:
  db_data:
